# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCIterate <- function(nIter, dat, old, old_ll, single, burn, N, n) {
    .Call('ConjointChecks_CCIterate', PACKAGE = 'ConjointChecks', nIter, dat, old, old_ll, single, burn, N, n)
}

